# Generated by Django 6.0 on 2025-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('full_name', models.CharField()),
                ('department', models.CharField()),
                ('dob', models.DateField()),
                ('gender', models.CharField()),
                ('address', models.CharField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
